// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1vzxoJem5FRoxoJkz1ajCvXlBTeH4NE',
    appId: '1:924317071482:web:c4dfefe8f5d9f891c5e3c3',
    messagingSenderId: '924317071482',
    projectId: 'fir-flutter-19d17',
    authDomain: 'fir-flutter-19d17.firebaseapp.com',
    storageBucket: 'fir-flutter-19d17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTTq8LwerM7P6HrRyMFyiFO3VzaiK78ro',
    appId: '1:924317071482:android:181f9642c9ee474fc5e3c3',
    messagingSenderId: '924317071482',
    projectId: 'fir-flutter-19d17',
    storageBucket: 'fir-flutter-19d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJeNiTo_d0yy0vHQh17nnbg1L_IvQFPCk',
    appId: '1:924317071482:ios:c86baebafddcfd7ec5e3c3',
    messagingSenderId: '924317071482',
    projectId: 'fir-flutter-19d17',
    storageBucket: 'fir-flutter-19d17.appspot.com',
    iosClientId: '924317071482-9umbi1dagj5kbh41lvr4iidkvu6qf37r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJeNiTo_d0yy0vHQh17nnbg1L_IvQFPCk',
    appId: '1:924317071482:ios:c86baebafddcfd7ec5e3c3',
    messagingSenderId: '924317071482',
    projectId: 'fir-flutter-19d17',
    storageBucket: 'fir-flutter-19d17.appspot.com',
    iosClientId: '924317071482-9umbi1dagj5kbh41lvr4iidkvu6qf37r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTest',
  );
}
